name = "InfoBLUP"
uuid = "c1ff173c-875a-4930-a8f1-749651dbc3d7"
authors = ["Zhixu Pang <pang_z_x@163.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
